### ISSUE TITLE
Gnome-shell crashed and dumped core when the extension turns on

### ISSUE THREAD

**Issue by karmicdude** [TimurKiyivinski/gnome-shell-screenshotlocations-extension#4]
System info: 
Archlinux, kernel Linux 4.10.6-1-ARCH / 4.10.6-1-zen (I tried both)
GNOME Shell 3.22.3 with systemd v. 232-8.
Xorg / Wayland (I tried both)

At the moment of activating the extension, the gnome crashes with core dumped and throws back to the gdm login screen. Attempts to log on to the system are unsuccessful, as long as you do not delete the extension in `~/.local/share/gnome-shell/extensions/screenshotlocations.timur@linux.com/`

[Full system log](https://pastebin.com/raw/DbtdYntP) from the moment of installing the extension, until the gdm login screen (I cleared journalctl logs before activation through extensions.gnome.org). 
And [full system log](https://pastebin.com/raw/6jZRdXFB) from the moment of first login attempt after installing the extension and the gnome re-crash.

**Comment by kiyui** [comment]
Hi, is this with the GNOME extension from this repository or from the website? Make sure you're using the latest as that solves that. The extension has been test on my system with the exact same specifications, as well as 3 other Arch systems from my friends so that's a bit odd.

**Comment by karmicdude** [comment]
What gnome package did you install? Minimal gnome-shell, gnome or gnome-meta?
I don't want to pollute the system with unnecessary packages and utils that I don't use, so I chose a clean gnome-shell without anything. There may be a problem in the lack of a component or library...

**Comment by kiyui** [comment]
As long as you have the base GNOME shell, with GLib and GIO (should be there) from the package `gobject-introspection` for example. It should be there.

Can you send me your list of packages so I can diff with mine?
`pacman -Qq`

**Comment by karmicdude** [comment]
`curl https://pastebin.com/raw/a29hMchg`

**Comment by kiyui** [comment]
Hey, it looks like you're missing `gobject-introspection`. Let me know of that solves it.

**Comment by karmicdude** [comment]
I already tried, but it doesn't

**Comment by karmicdude** [comment]
Today I was able to get work `Caffeine` and `gnome-shell-imgur` extensions. They behaved in the same way. 

I saw in log next line:

`Apr 04 11:31:05 zen gnome-shell[6812]: Cannot open pixbuf loader module file '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory`

Then I try to create `loaders.cache` with command:

`sudo sh -c 'gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'`

And this solved the problem with them, they ceased to lead to the crash of the gnome-shell. I was hoping that this would also solve the problem with `screenshotlocations` extension. But, unfortunately, no. 
I do not really need this extension, I just hoped that it would be useful to someone if I solve the problem. Moreover, in the comments on the extension.gnome.org, I saw someone have a similar problem.

**Comment by kiyui** [comment]
I see, can you check if the settings schema for `org.gnome.gnome-screenshot` exists in `dconf`? I think this may be the cause.

**Comment by kiyui** [comment]
Just curious, `gnome-screenshot` is not even installed. Do screenshots work without it? This extension depends on it.

**Comment by karmicdude** [comment]
this works, screenshots are saved to home dir and defaults keybindings for selection, window, etc works fine without `gnome-screenshot` tool
If I looked correctly, the schema is missing
```
gsettings list-schemas | grep screen
org.gnome.settings-daemon.plugins.screensaver-proxy
org.gnome.settings-daemon.peripherals.touchscreen
org.gnome.desktop.screensaver
org.gnome.login-screen
```

After installation `gnome-screenshot` the scheme appeared:
```
gsettings list-schemas | grep screenshot
org.gnome.gnome-screenshot
```
Ha, nice, everything is fine. Now extension works. Thx man.

**Comment by kiyui** [comment]
Interesting, glad it works! :+1:
