### ISSUE TITLE
[BUG] extension kills gnome shell

### ISSUE THREAD

**Issue by a2nt** [TimurKiyivinski/gnome-shell-screenshotlocations-extension#5]
After installing the extension X server was killed and automatically restarted.
Tried to login back, but X server was killed again.
Had to login as root and remove extension manually from user configuration.

Guess it was because I don't have gnome-screenshot app installed, but I'm able to make screenshots using keyboard combination set to Ctrl+Shift+1 and it would be nice to be able to define save location, but I don't have a key at dconf-editor

**Comment by kiyui** [comment]
That's odd, what operating system and GNOME version are you using?

You can configure the save location from the extension configuration screen in GNOME Tweak Tools, and yeah this does depend on `gnome-screenshot`.

**Comment by a2nt** [comment]
uname -a
Linux darkside 4.15.0-1-amd64 #1 SMP Debian 4.15.4-1 (2018-02-18) x86_64 GNU/Linux

**Comment by kiyui** [comment]
Stale issue
