### ISSUE TITLE
Update instructions to explain how to change screenshot location setting

### ISSUE THREAD

**Issue by Poikilos** [TimurKiyivinski/gnome-shell-screenshotlocations-extension#6]
Hello the readme says, "The save directory path and extension are defined under org.gnome.gnome-screenshot with the keys auto-save-directory and default-file-type. You can customize the save directory with the extension preference tool. A valid example would be /home/timur/Pictures/Screenshots for instance." However, I have no idea how to do that.

**Comment by kiyui** [comment]
Hi, sorry for that. Under the *extensions* tab in Gnome Tweak Tool, look for the *Screenshot locations* extension. It will look something like this:

![gnome tweak tool extension tab](https://user-images.githubusercontent.com/5292862/55927749-b737f380-5c05-11e9-8d76-16894d1ce4f3.png)

Click the gear/settings icon in that row and an interface like this should appear:

![Screenshot from 2019-04-11 11-00-25](https://user-images.githubusercontent.com/5292862/55927917-55c45480-5c06-11e9-8015-5e3a768660c5.png)

From there you can change the path. Make sure to have *Tweak Tool* installed first cause it does not come with all distros by default :smile: 

Also, I have not tested this under the newer GNOME versions so please let me know if you run into any issues :bowing_woman:

**Comment by Poikilos** [comment]
- This works well with GNOME 3.30.2 in Fedora 29.
- That documentation would be very clear for the readme, even without the pictures (gnome-tweak-tool is called "GNOME Tweaks" in the GNOME Software application).

Thanks!

**Comment by kiyui** [comment]
Stale, GNOME has made it a lot easier to access preferences since this issue was created.
