### ISSUE TITLE
not working on gnome-shell 3.36

### ISSUE THREAD

**Issue by derVedro** [TimurKiyivinski/gnome-shell-screenshotlocations-extension#9]
I think gnome guys are not using gnome-screenshot anymore but implement something into gnome-shell itself. So there is no way to tweak the output directory throw dconf. I feel like it works a little bit faster, but is too bad that there is no way to configure stuff like with gnome-screenshot.

**Comment by kiyui** [comment]
I'm also somewhat bumped about this, and what this plugin essentially does is set up the same keyboard shortcuts to run the `gnome-screenshot` command. For now, I think you can give #8 a try. Sorry about that :grimacing:
